image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - wakatime.vscode-wakatime
    - johnpapa.winteriscoming
    - vscode-icons-team.vscode-icons
    - esbenp.prettier-vscode
    - naumovs.color-highlight
    - dsznajder.es7-react-js-snippets
    - asciidoctor.asciidoctor-vscode
    - jpoissonnier.vscode-styled-components

tasks:
- name: Configure API Host ENV URL
  command: echo "REACT_APP_API_HOST=$(/usr/bin/gp url 8080)" >> /workspace/igti-react-agenda/frontend/.env
- name: 'Backend: start'
  init: |
    cd backend
    npm i
  command: |
    cd backend
    npm start
- name: 'Frontend: start'
  init: |
    cd frontend
    npm i
  command: |
    cd frontend
    npm start

ports:
  - port: 8080 # backend
    visibility: public
    onOpen: ignore
  - port: 3000 # frontend
    visibility: public
    onOpen: open-preview